# Generated by Django 3.1.2 on 2020-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glyph_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinletter',
            name='pronunciation',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
