# Generated by Django 3.1.2 on 2020-10-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glyph_app', '0002_joinletter_pronunciation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinletter',
            old_name='pronunciation',
            new_name='join_letter_pronunciation',
        ),
    ]
