# Generated by Django 3.1.2 on 2020-10-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glyph_app', '0003_auto_20201004_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinletter',
            name='letter_category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinletter',
            name='letters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glyph_app.letter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_category',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
