# Generated by Django 3.1.2 on 2020-10-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glyph_app', '0004_auto_20201004_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinletter',
            name='letter_category',
        ),
        migrations.RemoveField(
            model_name='joinletter',
            name='letters',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='letter_category',
        ),
    ]
